files:
  - source: /WoWsShipBuilder.UI/Translations/Translation.resx
    translation: /WoWsShipBuilder.UI/Translations/Translation.%locale%.resx
  - source: /WoWsShipBuilder.Core/DataUI/UnitTranslations/UnitLocalization.resx
    translation: /WoWsShipBuilder.Core/DataUI/UnitTranslations/UnitLocalization.%locale%.resx
