files:
  - source: /WoWsShipBuilder.Common/Infrastructure/Localization/Resources/Translation.resx
    translation: /WoWsShipBuilder.Common/Infrastructure/Localization/Resources/Translation.%locale%.resx
    update_option: update_as_unapproved
