files:
  - source: /WoWsShipBuilder.Core/Localization/Translation.resx
    translation: /WoWsShipBuilder.Core/Localization/Translation.%locale%.resx
  - source: /WoWsShipBuilder.Core/DataUI/UnitTranslations/UnitLocalization.resx
    translation: /WoWsShipBuilder.Core/DataUI/UnitTranslations/UnitLocalization.%locale%.resx
