version: "3.8"
services:
#  socket-proxy:
#    image: tecnativa/docker-socket-proxy
#    ports:
#      - "2375:2375"
#    privileged: true

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus-config:/etc/prometheus
      - prometheus-data:/prometheus
    ports:
      - target: 9090
        published: 9090
        mode: host
    networks:
      - monitoring

  cAdvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080:8080"
    networks:
      - monitoring

networks:
  monitoring:
    name: monitoring
#  socket-access:

volumes: 
  prometheus-data:
  prometheus-config:
    external: true
