version: "2.4"
services: 
  grafana:
    image: grafana/grafana-oss
    ports:
      - "8084:3000"
    container_name: grafana
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - local
volumes:
  grafana-data: