services: 
  app:
    build: 
      context: ../../.
      dockerfile: WoWsShipBuilder.Web/Dockerfile
    ports:
      - "8082:443"
      - "8081:80"
    networks:
      - local
    container_name: "wowssb-app"
    environment:
      SENTRY_DSN:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    ports:
      - "9090:9090"
    networks: 
      - local
  cAdvisor:
    image: gcr.io/cadvisor/cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    networks: 
      - local

networks:
  local:
volumes: 
  prometheus-data:
    external: true