apiVersion: 11
deleteDatasources:
  - name: Prometheus
    orgId: 1
dataSources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true