name: Build and create release

on: 
  push:
    tags:
      - 'v*'

jobs: 
  build-and-release:
    runs-on: windows-latest
    name: Build and release application

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.x
      - name: Process tag version
        run: echo ("CURRENT_TAG=" + $env:GITHUB_REF.Replace('refs/tags/v', '')) >> $env:GITHUB_ENV
      - name: Create application config
        run: echo "${{ secrets.SHIPBUILDER_APPCONFIG }}" >> WoWsShipBuilder.UI\Settings\ApplicationOptions.json
      - name: Restore dependencies
        run: dotnet restore
      - name: Build application
        run: dotnet build --no-restore -c Release
      - name: Test application
        run: dotnet test --no-build -c Release --verbosity normal
        
      - name: Publish windows executable
        run: dotnet publish WoWsShipBuilder.UI -p:PublishProfile=PublishWindows -p:Version="$env:CURRENT_TAG"
      - name: Package published binary
        run: dotnet pack WoWsShipBuilder.UI -c Release -p:NuspecFile=WoWsShipBuilder.nuspec -p:NuspecBasePath=bin/Release/net5.0/publish /p:version=1.0.0 -p:NuspecProperties=version="$env:CURRENT_TAG"
      - name: Create squirrel release
        working-directory: WoWsShipBuilder.UI
        run: $env:USERPROFILE\.nuget\packages\Clowd.Squirrel\tools\Squirrel.com --releasify .\bin\Release\WoWsShipBuilder.$env:CURRENT_TAG.nupkg --selfContained --releaseDir=".\releases"
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with: 
          files: WoWsShipBuilder.UI\releases\*
          body_path: ReleaseNotes.md