name: Requirement check for merges with main.

on:
  pull_request:
    branches:
      - release/desktop

jobs:
  build-and-release:
    runs-on: windows-latest
    name: Release build and version check

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Build application
        run: dotnet build dirs.proj -c Release -p:ReleaseTest=true
      - name: Test application
        run: dotnet test dirs.proj --no-build -c Release -p:ReleaseTest=true --verbosity normal

  verify-squirrel-release:
    runs-on: windows-latest
    name: Verify squirrel release process

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Run SquirrelBuildAndRelease
        run: Tools\SquirrelBuildAndRelease.ps1
        shell: powershell
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: releases/WoWsShipBuilderSetup.exe
          retention-days: 5
