name: Build and run tests.

on:
  push:
    branches-ignore:
      - 'release/**'
      - 'development'
      - 'l10n_development'
    paths-ignore:
      - '**/*.md'
      - '.github/*.png'
      - 'docs/**/*.*'
      - 'workflows/*.yml'
      - 'deployment/**/*.*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    name: Build application

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Restore dependencies
        run: dotnet restore dirs.proj
      - name: Build application in Debug mode
        run: dotnet build dirs.proj --no-restore -c Debug -p:TreatWarningsAsErrors=true
      - name: Build application in Release mode
        run: dotnet build dirs.proj --no-restore -c Release -p:TreatWarningsAsErrors=true
      - name: Test application in Release mode
        run: dotnet test dirs.proj --no-build -c Release --verbosity normal

  build-and-test-windows:
    runs-on: windows-latest
    name: Build application (Windows)

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Restore dependencies
        run: dotnet restore dirs.proj
      - name: Build application in Debug mode
        run: dotnet build dirs.proj --no-restore -c Debug -p:TreatWarningsAsErrors=true
      - name: Build application in Release mode
        run: dotnet build dirs.proj --no-restore -c Release -p:TreatWarningsAsErrors=true
      - name: Test application in Release mode
        run: dotnet test dirs.proj --no-build -c Release --verbosity normal
