name: Add new issue to project

on:
  issues:
    types:
      - opened

jobs: 
  automate-project-assignment:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: WoWs ShipBuilder Development
          column: Triage
          repo-token: ${{ secrets.GITHUB_TOKEN }}
