name: Requirement check for merges with main.

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    name: Release build and version check

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Build application
        run: dotnet build -c ReleaseTest
      - name: Test application
        run: dotnet test --no-build -c ReleaseTest --verbosity normal
