name: Web Docker Build

on:
  push:
    branches:
      - 'development'
      - 'main'
      - 'release/web/v*'
    paths-ignore:
      - 'deployment/**/*.*'
  workflow_dispatch:

jobs:
  buildApp:
    runs-on: ubuntu-latest
    name: Build image

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dotnet/nbgv@master
        with:
          setAllVars: true
          path: WoWsShipBuilder.Web
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/wows-builder-team/wowssb:${{ env.NBGV_NuGetPackageVersion }}
          file: WoWsShipBuilder.Web/Dockerfile
